### ISSUE TITLE
Problem running the Tophat Fusion Pre (fusions.out) results

### ISSUE THREAD

**Issue by KeyTals** [yhoogstrate/fuma#40]
I am getting the following error when i try to run the tophat fusion pre results. I have filter the tophat fusion (fusions.out) results but dint change the format. (i am also attaching this file here)
[tmp1.tophat.fusions.out.txt](https://github.com/yhoogstrate/fuma/files/728163/tmp1.tophat.fusions.out.txt)

Here is the error

2017-01-24 17:48:02,834 - FuMa::Readers::ReadTophatFusionPre - INFO - Parsing file: tmp1
2017-01-24 17:48:02,838 - FuMa::Readers::ReadRNASTARFusionFinal - INFO - Parsing file: /is2/projects/CCR-SF/scratch/illumina/Processing/ANALYSIS/DATA/talsaniaks/gene_fusion/star_fusion/GH2489/star-fusion.fusion_candidates.final
2017-01-24 17:48:02,842 - FuMa::ComparisonTriangle - INFO - Starting 11325 comparisons for k=1
Traceback (most recent call last):
  File "/opt/nasapps/development/fuma/3.0.3/bin/fuma", line 4, in <module>
    __import__('pkg_resources').run_script('fuma==3.0.3', 'fuma')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 724, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1656, in run_script
  File "/opt/nasapps/development/fuma/3.0.3/lib/python2.7/site-packages/fuma-3.0.3-py2.7.egg/EGG-INFO/scripts/fuma", line 225, in <module>

  File "build/bdist.linux-x86_64/egg/fuma/ComparisonTriangle.py", line 90, in overlay_fusions
  File "build/bdist.linux-x86_64/egg/fuma/ComparisonTriangle.py", line 217, in export_list_chunked
  File "build/bdist.linux-x86_64/egg/fuma/ComparisonTriangle.py", line 177, in export_list_fg
  File "build/bdist.linux-x86_64/egg/fuma/Fusion.py", line 268, in get_annotated_genes_left2
Exception: Requested empty gene list

**Comment by yhoogstrate** [comment]
Ouch, a bug, I will dive into this! Thanks for reporting @KeyTals !!

**Comment by yhoogstrate** [comment]
@KeyTals I think you have something wrong in the input. It seems like the gene-set is not properly linked to the sample. Could you provide the command line arguments you provided?

**Comment by KeyTals** [comment]
You are correct, I must have done some thing wrong when i was running the fuma. following commad is working fine.

fuma -a "hg38:hg38.ens84.bed" -s "StarFusion:star-fusion_final:star-fusion.fusion_candidates.final" "TophatFusion:tophat-fusion_pre:tmp1.tophat.fusions.out.txt" -f "list" -o "fuma.txt" -l  "TophatFusion:hg38" "StarFusion:hg38" -m "overlap" --no-strand-specific-matching -g "0"

2017-02-02 09:08:52,484 - FuMa::ParseBED - INFO - Parsing BED file: /is2/projects/CCR-SF/scratch/illumina/Processing/ANALYSIS/DATA/talsaniaks/gene_fusion/fuma/hg38.ens84.bed
2017-02-02 09:08:54,553 - FuMa::Readers::ReadRNASTARFusionFinal - INFO - Parsing file: /is2/projects/CCR-SF/scratch/illumina/Processing/ANALYSIS/DATA/talsaniaks/gene_fusion/star_fusion/GH2489/star-fusion.fusion_candidates.final
2017-02-02 09:08:54,589 - FuMa::Readers::ReadTophatFusionPre - INFO - Parsing file: tmp1.tophat.fusions.out.txt
2017-02-02 09:08:54,602 - FuMa::Readers::ReadTophatFusionPre - INFO - Duplication removal: TophatFusion (134 fusions)
2017-02-02 09:08:54,608 - FuMa::Readers::ReadRNASTARFusionFinal - INFO - Duplication removal: StarFusion (16 fusions)
2017-02-02 09:08:54,618 - FuMa::ComparisonTriangle - INFO - Starting 8128 comparisons for k=1

Keyur

**Comment by yhoogstrate** [comment]
Awesome! Is it okay I close this issue?

**Comment by KeyTals** [comment]
Sure, Close the ticket.

Keyur
